name: docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker build
      uses: actions/setup-go@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: hugogbs 
        password: ${{ secrets.SENHA_DOCKER_HUB }}
    
