name: docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
   
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker build
      uses: actions/setup-go@v4

    - name: use artifact
      uses: actions/download-artifact@v3
      with:
        # nome do progrma vem do nome do articatc criado no CIgo.yml
        name: programa

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: hugogbs 
        password: ${{ secrets.SENHA_DOCKER_HUB }}

    - name: Build and push docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: hugogbs/go_ci:{{github.ref_name}}
    
